# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://jungmokoo.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Jungmo Koo
# Description of the Site
#description: I am an AI researcher
description:
  "
  <br>
  <i>The only limit is your imagination.</i><br>
  <i>유일한 한계는 우리의 상상력이다.</i><br>
  "
# URL of Image of the Site
site-image: ../images/ai_bg.jpg
# Keywords of the Site
site-keywords: AI, Research, Deep learning, Blog, Jungmo Koo
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
#heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: https://raw.githubusercontent.com/JungmoKoo/jungmokoo.github.io/master/assets/images/ai_bg.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
#heroimage: ../images/ai_bg.jpg
#heroimage: "../assets/images/ai_bg.jpg"

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: gooj978@gmail.com
facebook_username: /
twitter_username: /
instagram_username: jungmographer
linkedin_username: jungmokoo
github_username:  jungmokoo
youtube_channel_id: UCl_YmO5FEfPdKOnRuIevdYg
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: /

# Disqus
disqus-shortname: /

# Name of the Author
author-name: Jungmo Koo
# URL for the Image of the Author
#author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
author-image: "../assets/images/JM.jpg"
# 60 Words About the Author
author-about:
#<b>Research interest</b><br>
#Artificial intelligence in computer vision<br>
# - I aim for recognition systems that can be run in a real world environment.<br>
#<br>
#<b>Education</b><br>
# - "Ph.D. in Electrical Engineering (Adviser: Prof. Hyun Myung) / KAIST / Feb. 2017 - Present"<br>
# - M.S. in Civil and Environmental Engineering (Adviser: Prof. Hyun Myung) / KAIST / Feb. 2015 - Feb. 2017<br>
# - B.S. in Electronic Engineering / Kyung Hee Univ. / Mar. 2009 - Feb. 2015<br>
#<br>
# <b>Experience</b><br>
# - [WORK] Seadronix Corp. / Team leader / Mar. 2020 - Feb. 2021<br>
# - [CLASS] Intelligent robot experiment(RE510, KAIST) / General assistant / Feb. 2015 - Feb. 2017<br>
# - [CHALLENGE] DJI Developer Challenge / Finalist / Feb. 2015 - Feb. 2017<br>
# - [WORK] KRISO (Korea Research Institute of Ships & Ocean Engineering) / Research intern / June 2015 - July 2015<br>

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.linkedin.com/in/jungmo-koo/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
